### ISSUE TITLE
footer is obscuring main content

### ISSUE THREAD

**Issue by jidicula** [MIBS/mibs.github.io#4]
![screen shot 2016-12-09 at 5 22 00 pm](https://cloud.githubusercontent.com/assets/12765385/21066539/0b2052ac-be34-11e6-9278-ce4216997f53.png)

**Comment by zafarali** [comment]
Hi!

Thanks for bringing this to our attention. If you would like to fork and
make a contribution go ahead, if not I'll end up doing this sometime next
week!

Cheers,
Zaf
